name: C++ CI Build

on:
  push:
    branches: ["main", "master"]
    paths-ignore:
      - "**.md"
      - "docs/**" # 如果你有文档目录也可以加上
      - ".github/workflows/**"
      - ".gitignore" # 忽略配置文件修改
      - ".gitattributes"
  pull_request:
    branches: ["main", "master"]
    paths-ignore:
      - "**.md"
      - "docs/**" # 如果你有文档目录也可以加上
      - ".github/workflows/**"
      - ".gitignore" # 忽略配置文件修改
      - ".gitattributes"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev libomp-dev cmake g++

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          vcpkg install opencv:x64-windows

      - name: Configure CMake
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            # Windows 平台：使用 vcpkg 工具链
            cmake -B build \
              -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" \
              -DVCPKG_TARGET_TRIPLET=x64-windows
          else
            # Linux 平台：直接 Configure 即可
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
          fi
        shell: bash

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release -j 2

      - name: Run Ray Tracer
        run: |
          cd bin
          ./rayt scene.aur

      - name: Upload Result Image
        uses: actions/upload-artifact@v4
        with:
          name: rendered-scene-${{ matrix.os }}
          path: bin/*.png
